version: "3"
services:
  test:
    build: .
    ports:
      - "4500:4500"
    container_name: gfw-analysis-gee-test
    environment:
      PORT: 4500
      DEBUG: "True"
      GATEWAY_URL: http://mymachine:9000
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      LOCAL_URL: http://mymachine:4500
      EE_PRIVATE_KEY: ${EE_PRIVATE_KEY}
      API_VERSION: v1
      REDIS_URL: redis://redis:6379
      CARTODB_USER: wri-01
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
    command: test
    depends_on:
      - redis
  redis:
    image: redis
