from gfwanalysis.routes.api.v1.biomass_loss_router import biomass_loss_endpoints_v1
from gfwanalysis.routes.api.v1.forma250_router import forma250_endpoints_v1
from gfwanalysis.routes.api.v1.hansen_router import hansen_endpoints_v1
from gfwanalysis.routes.api.v1.highres_router import highres_tiles_endpoints_v1
from gfwanalysis.routes.api.v1.histogram_router import histogram_endpoints_v1
from gfwanalysis.routes.api.v1.landcover_router import landcover_endpoints_v1
from gfwanalysis.routes.api.v1.landsat_router import landsat_tiles_endpoints_v1
from gfwanalysis.routes.api.v1.recent_router import recent_tiles_endpoints_v1
from gfwanalysis.routes.api.v1.sentinel_router import sentinel_tiles_endpoints_v1
from gfwanalysis.routes.api.v1.soil_carbon_router import soil_carbon_endpoints_v1
from gfwanalysis.routes.api.v1.whrc_biomass_router import whrc_biomass_endpoints_v1
